name: News App CI/CD

on:
  push:
    branches: [ feature-1 ]
  pull_request:

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Check & Install Java 17
      run: |
        echo "Checking Java"
        if java -version >/dev/null 2>&1; then
            echo "Java already installed"
            java -version
        else
            echo "Installing Java 17..."
            sudo apt update -y
            sudo apt install -y openjdk-17-jdk
            java -version
        fi


    - name: Check & Install Maven
      run: |
        echo "=== Checking Maven ==="
        if mvn -version >/dev/null 2>&1; then
            echo "Maven already installed"
            mvn -version
        else
            echo "Installing Maven..."
            sudo apt install -y maven
            mvn -version
        fi

    
    - name: Check & Install Tomcat 10
      run: |
        echo "Checking Tomcat installation"
        if [ -d "/opt/apache-tomcat-10.1.49" ]; then
            echo "Tomcat already installed"
        else
            echo "Installing Tomcat 10..."
            cd /opt
            sudo wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.49/bin/apache-tomcat-10.1.49.tar.gz
            sudo tar -xzf apache-tomcat-10.1.49.tar.gz
            sudo mv apache-tomcat-10.1.49 /opt/tomcat10
            sudo chmod +x /opt/tomcat10/bin/*.sh
        fi


    - name: Build WAR File
      run: |
  
        mvn clean package -DskipTests


    - name: Deploy WAR to Tomcat
      run: |
       echo "Stopping Tomcat"
       sudo /opt/tomcat10/bin/shutdown.sh || true

       echo "Removing old deployment"
       sudo rm -rf /opt/tomcat10/webapps/news-app
       sudo rm -f /opt/tomcat10/webapps/news-app.war

       echo "Deploying new WAR"
       sudo cp target/news-app.war /opt/tomcat10/webapps/

       echo "Starting Tomcat"
       sudo /opt/tomcat10/bin/startup.sh
       sleep 15
        
    - name: Status check
      run: |
        curl -I http://35.154.58.116:8080/news-app/ || true
        
    - name: Verify app content
      run: |
       RESPONSE=$(curl -s http://35.154.58.116:8080/news-app/)
       echo "$RESPONSE" | grep "Welcome to news App" || true
       echo "$RESPONSE" | grep "Live News Categories" || true
       echo "$RESPONSE" | grep "Top Headlines" || true
        sleep 60
       echo "Stopping Tomcat"
       sudo /opt/tomcat10/bin/shutdown.sh || true
